"""Valid counterfactuals for safety responsibility: filters the motion
model's motion set (Eq. 1a) before the CVaR of Eq. 3.

The paper's motion set is everything the motion model deems possible for
agent a at step k. Measured on CAT's 500 scenes with DenseTNT, that set
mixes in alternatives no driver in a's place had: 27% of the samples leave
a's logged route by more than 3.5 m within 8 s (another intent: "it could
have turned right instead of crossing"), and nothing stops a sample from
leaving the road, driving through a third vehicle or accelerating beyond
what a car can. The upper-tail CVaR picks exactly the samples that stray
furthest. These filters keep only the alternatives that execute a's own
intent differently -- the trajectories stay the motion model's (sampled,
or its whole probability-weighted set); nothing is generated by rule:

  lane_route  same intent, by lanes (responsibility.lanes): a goal-based
              model's goal distribution is restricted, before anything is
              sampled, to the goals within ``lane_radius`` of a lane of the
              agent's logged route -- the lanes it runs along, their side
              neighbours (a lane change keeps the intent) and everything
              reachable after the log ends; a model without goals has its
              trajectories' end points checked instead.
  intent      same intent without lane topology (responsibility.intent),
              for maps built by perception: at the last logged step the
              trajectory heads within ``intent_heading`` (deg) of the logged
              path where it is, it stays within ``intent_lateral`` (m) of
              that path, and with ``intent_edges`` it is never across a road
              edge from it.
  route       same intent: every point of the trajectory, over the steps
              the log covers, within ``route_tolerance`` (m) of a's logged
              route (its logged future path, extended 100 m along its last
              heading: responsibility.geometry.logged_route). Speed,
              timing and the position within the lane stay free.
  drivable    every point (every 0.5 s) within ``drivable_half_width`` (m)
              of a vehicle lane centreline of the map (LANE_FREEWAY,
              LANE_SURFACE_STREET, LANE_UNDEFINED).
  drivable_edges  the trajectory, driven from a's position, crosses no road
              edge that a's own logged path does not cross
              (responsibility.edges); a gap in the edges removes nothing.
              For a map built by perception, which has no centrelines
              inside intersections, this replaces ``drivable``.
  kinematics  from speeds averaged over 0.5 s: longitudinal acceleration
              within [-max_decel, max_accel] (m/s^2), the first 0.5 s
              included (from a's current speed), and lateral acceleration
              (speed x heading rate) at most ``max_lat_accel``.
  collision   (per neighbour b) no footprint overlap, over the metric
              horizon, with any other agent's logged future -- except b,
              whose distance is what is being measured, and agents a's own
              logged future overlaps as well (box noise in the data).

The filters apply in that order, each only if it leaves at least one
trajectory; if no trajectory left follows the route, the one of them that
strays least is kept, so beta_s stays defined. The probabilities of what is kept are
renormalised (weighted_cvar normalises its weights).
"""

import copy
from dataclasses import dataclass
from typing import Dict, Optional, Sequence

import numpy as np
import torch

from responsibility.edges import crosses_road_edge
from responsibility.geometry import BoxTrajectories, collision_cost_matrix, lateral_deviation, logged_route
from responsibility.intent import crosses_edge, same_heading
from responsibility.lanes import lane_graph, route_lanes
from responsibility.scene import Scene

DRIVABLE_LANE_TYPES = ("LANE_FREEWAY", "LANE_SURFACE_STREET", "LANE_UNDEFINED")
DT = 0.1  # s per step
KIN_STEP = 5  # steps per speed average (0.5 s)
MIN_TURN_SPEED = 1.0  # m/s: below this the heading of a displacement is noise
COLLISION_MARGIN = -0.2  # m: circle overlap tolerated (box and prediction noise)
ORDER = ("lane_route", "intent", "route", "drivable", "drivable_edges", "kinematics")
NEGLIGIBLE = 1e-7  # goals below this probability are left out of the lane test (dropped if restricted)


@dataclass
class MotionFilterConfig:
    lane_route: bool = False
    lane_radius: float = 2.0  # m from a lane centreline (99% of DenseTNT's goal mass lies within 2 m of one)
    intent: bool = False  # same intent from the trajectories (and road edges), no lanes needed
    intent_heading: float = 45.0  # deg from the logged path's direction where the trajectory is, at T*
    intent_lateral: Optional[float] = 8.0  # m from the logged path; None: no lateral test
    intent_edges: bool = False  # also never across a road edge from the logged path
    route_tolerance: Optional[float] = None  # m; None: no route filter
    drivable_half_width: Optional[float] = None  # m; None: no drivable filter
    drivable_edges: bool = False  # the path crosses no road edge
    kinematics: bool = False
    max_accel: float = 5.0  # m/s^2
    max_decel: float = 9.0  # m/s^2 (an emergency stop is about 8)
    max_lat_accel: float = 7.0  # m/s^2
    collision: bool = False

    @property
    def active(self) -> bool:
        return (self.lane_route or self.intent or self.route_tolerance is not None or self.drivable_half_width is not None
                or self.drivable_edges
                or self.kinematics or self.collision)


def with_log_prob(dist, log_prob):
    """A copy of a goal distribution with other log-probabilities."""
    out = copy.copy(dist)
    out.log_prob = log_prob
    return out


def goals_on_lanes(dist, lanes, radius: float, scene: Scene) -> np.ndarray:
    """Which goals [G] of a goal distribution lie within ``radius`` of the
    lanes (goals of negligible probability: False)."""
    p = dist.log_prob.detach().exp().cpu().numpy()
    live = np.flatnonzero(p > NEGLIGIBLE)
    out = np.zeros(len(p), dtype=bool)
    out[live] = lane_graph(scene).near(np.asarray(dist.goals_global)[live], lanes, radius)
    return out


def restrict_to_route(scene: Scene, agent: int, step: int, dist, cfg: MotionFilterConfig):
    """(distribution, mass): a goal-based model's distribution restricted to
    the goals on the agent's route lanes and renormalised, with the
    probability mass that lay on them -- or (dist, None) unchanged for a
    model without goals, an agent on no lane, or no goal on the route."""
    if getattr(dist, "goals_global", None) is None:
        return dist, None
    lanes = route_lanes(scene, agent, step)
    if lanes is None:
        return dist, None
    on = goals_on_lanes(dist, lanes, cfg.lane_radius, scene)
    if not on.any():
        return dist, 0.0
    mask = torch.as_tensor(on, device=dist.log_prob.device)
    mass = float(dist.log_prob.exp()[mask].sum())
    log_prob = torch.where(mask, dist.log_prob, torch.full_like(dist.log_prob, -torch.inf))
    return with_log_prob(dist, log_prob - torch.logsumexp(log_prob, 0)), mass


def route_deviation(scene: Scene, agent: int, step: int, trajs: np.ndarray) -> np.ndarray:
    """Each trajectory's largest distance [N] from the agent's logged route,
    over the steps after ``step`` the log covers."""
    n_fut = min(trajs.shape[1], scene.n_steps - 1 - step)
    fut = slice(step + 1, step + 1 + n_fut)
    valid = scene.valid[agent, fut]
    pos = torch.as_tensor(scene.position[agent, fut, :2], dtype=torch.float64)
    if valid.any():
        last = step + 1 + int(np.flatnonzero(valid).max())
    else:
        last = step
    route = logged_route(torch.as_tensor(scene.position[agent, step, :2], dtype=torch.float64), pos,
                         torch.as_tensor(valid), torch.tensor(float(scene.heading[agent, last]), dtype=torch.float64))
    points = torch.as_tensor(trajs[:, :n_fut], dtype=torch.float64)
    dev = lateral_deviation(points, route)  # [N, n_fut]
    dev = dev.masked_fill(~torch.as_tensor(valid)[None], 0.0)  # only where the log says where the route goes
    return dev.amax(dim=-1).numpy() if n_fut else np.zeros(len(trajs))


def lane_points(scene: Scene, spacing: float = 1.0) -> np.ndarray:
    """Points [M, 2] along the scene's vehicle lane centrelines, at most
    ``spacing`` (m) apart (map polylines can have long straight segments)."""
    out = []
    for f in scene.map_features.values():
        poly = np.asarray(f.get("polyline", []), dtype=float)
        if f.get("type") not in DRIVABLE_LANE_TYPES or poly.ndim != 2 or len(poly) == 0:
            continue
        poly = poly[:, :2]
        out.append(poly[:1])
        for a, b in zip(poly[:-1], poly[1:]):
            n = max(1, int(np.ceil(np.linalg.norm(b - a) / spacing)))
            out.append(a + (b - a) * (np.arange(1, n + 1)[:, None] / n))
    return np.concatenate(out) if out else np.zeros((0, 2))


def drivable(scene: Scene, trajs: np.ndarray, half_width: float, points: Optional[np.ndarray] = None) -> np.ndarray:
    """Whether every point of each trajectory [N] (checked every 0.5 s) lies
    within ``half_width`` of a lane centreline (all True on a map without
    lanes). The 1 m spacing of the centreline points adds at most 0.5 m."""
    points = lane_points(scene) if points is None else points
    if len(points) == 0:
        return np.ones(len(trajs), dtype=bool)
    probe = trajs[:, KIN_STEP - 1::KIN_STEP]  # [N, K, 2]
    lo, hi = probe.reshape(-1, 2).min(0) - half_width - 1, probe.reshape(-1, 2).max(0) + half_width + 1
    near = points[np.all((points >= lo) & (points <= hi), axis=-1)]  # only the map around the trajectories
    if len(near) == 0:
        return np.zeros(len(trajs), dtype=bool)
    flat = torch.as_tensor(probe.reshape(-1, 2), dtype=torch.float32)
    ref = torch.as_tensor(near, dtype=torch.float32)
    nearest = torch.cat([torch.cdist(c, ref).amin(-1) for c in flat.split(8192)])
    return (nearest.view(probe.shape[:2]) <= half_width).all(-1).numpy()


def _wrap(angle):
    return (angle + np.pi) % (2 * np.pi) - np.pi


def kinematically_feasible(trajs: np.ndarray, start: np.ndarray, speed0: float, cfg: MotionFilterConfig) -> np.ndarray:
    """Whether each trajectory [N] keeps its 0.5 s-averaged longitudinal and
    lateral accelerations within the limits, from the current position
    ``start`` and speed ``speed0``."""
    n = (trajs.shape[1] // KIN_STEP) * KIN_STEP
    pts = np.concatenate([np.broadcast_to(start, (len(trajs), 1, 2)), trajs[:, KIN_STEP - 1:n:KIN_STEP]], axis=1)
    disp = np.diff(pts, axis=1)  # [N, K, 2] over 0.5 s each
    dt = KIN_STEP * DT
    speed = np.linalg.norm(disp, axis=-1) / dt  # [N, K], mean speed of each 0.5 s
    # the first average is centred 0.25 s after the current (instantaneous) speed
    accel = np.concatenate([(speed[:, :1] - speed0) / (dt / 2), np.diff(speed, axis=1) / dt], axis=1)
    ok = (accel <= cfg.max_accel).all(-1) & (accel >= -cfg.max_decel).all(-1)
    heading = np.arctan2(disp[..., 1], disp[..., 0])
    moving = (speed[:, 1:] > MIN_TURN_SPEED) & (speed[:, :-1] > MIN_TURN_SPEED)
    rate = np.abs(_wrap(np.diff(heading, axis=1))) / dt
    lat = np.where(moving, rate * 0.5 * (speed[:, 1:] + speed[:, :-1]), 0.0)
    return ok & (lat <= cfg.max_lat_accel).all(-1)


def _boxes(pos: np.ndarray, heading: np.ndarray, valid: np.ndarray, length, width) -> BoxTrajectories:
    f = torch.float32
    return BoxTrajectories(pos=torch.as_tensor(pos, dtype=f), heading=torch.as_tensor(heading, dtype=f),
                           valid=torch.as_tensor(valid), length=torch.as_tensor(length, dtype=f),
                           width=torch.as_tensor(width, dtype=f))


def _path_heading(trajs: np.ndarray, start: np.ndarray, heading0: float) -> np.ndarray:
    """Heading along each trajectory [N, T]: its direction of travel, held
    at the last one (initially the agent's heading) while it barely moves."""
    prev = np.concatenate([np.broadcast_to(start, (len(trajs), 1, 2)), trajs[:, :-1]], axis=1)
    d = trajs - prev
    moving = np.linalg.norm(d, axis=-1) > MIN_TURN_SPEED * DT
    out = np.empty(trajs.shape[:2])
    current = np.full(len(trajs), heading0, dtype=float)
    for t in range(trajs.shape[1]):
        current = np.where(moving[:, t], np.arctan2(d[:, t, 1], d[:, t, 0]), current)
        out[:, t] = current
    return out


def collisions(scene: Scene, agent: int, step: int, trajs: np.ndarray, horizon: int,
               others: Sequence[int]) -> np.ndarray:
    """[N, len(others)]: whether each trajectory's footprint overlaps each
    other agent's logged future within ``horizon`` steps. Agents the agent's
    own logged future overlaps too are never counted (box noise)."""
    others = list(others)
    if not others or horizon == 0:
        return np.zeros((len(trajs), len(others)), dtype=bool)
    fut = slice(step + 1, step + 1 + horizon)
    length, width = scene.shape_at(agent, step)[:2]
    start = scene.position[agent, step, :2]
    head = _path_heading(trajs[:, :horizon], start, float(scene.heading[agent, step]))
    ego = _boxes(trajs[:, :horizon], head, np.ones(head.shape, dtype=bool),
                 np.full(len(trajs), length), np.full(len(trajs), width))
    them = _boxes(scene.position[others, fut, :2], scene.heading[others, fut], scene.valid[others, fut],
                  [scene.shape_at(c, step)[0] for c in others], [scene.shape_at(c, step)[1] for c in others])
    hit = collision_cost_matrix(ego, them, margin=COLLISION_MARGIN).numpy() > 0
    actual = _boxes(scene.position[agent, fut, :2][None], scene.heading[agent, fut][None], scene.valid[agent, fut][None],
                    [length], [width])
    logged_hit = collision_cost_matrix(actual, them, margin=COLLISION_MARGIN).numpy()[0] > 0
    return hit & ~logged_hit[None]


class MotionFilter:
    """The filters of one agent's motion set at one step: ``keep(b)`` gives
    the indices to compute beta_s(a, b) over, and ``stats(keep)`` what was
    kept."""

    def __init__(self, scene: Scene, agent: int, step: int, trajs: np.ndarray, horizon: int,
                 neighbours: Sequence[int], cfg: MotionFilterConfig, weights: Optional[np.ndarray] = None,
                 goals_restricted: bool = False):
        self.cfg, self.n = cfg, len(trajs)
        self.weights = weights
        self.masks: Dict[str, np.ndarray] = {}
        self.deviation = None
        if cfg.lane_route and not goals_restricted:  # a model without goals: the end points
            lanes = route_lanes(scene, agent, step)
            if lanes is not None:
                self.masks["lane_route"] = lane_graph(scene).near(trajs[:, -1], lanes, cfg.lane_radius)
        if cfg.route_tolerance is not None or (cfg.intent and cfg.intent_lateral is not None):
            self.deviation = route_deviation(scene, agent, step, trajs)
        if cfg.intent:
            keep = same_heading(scene, agent, step, trajs, cfg.intent_heading)
            if cfg.intent_lateral is not None:
                keep &= self.deviation <= cfg.intent_lateral
            if cfg.intent_edges:
                keep &= ~crosses_edge(scene, agent, step, trajs)
            self.masks["intent"] = keep
        if cfg.route_tolerance is not None:
            self.masks["route"] = self.deviation <= cfg.route_tolerance
        if cfg.drivable_half_width is not None:
            self.masks["drivable"] = drivable(scene, trajs, cfg.drivable_half_width)
        if cfg.drivable_edges:
            self.masks["drivable_edges"] = ~crosses_road_edge(scene, agent, step, trajs)
        if cfg.kinematics:
            self.masks["kinematics"] = kinematically_feasible(
                trajs, scene.position[agent, step, :2], float(np.linalg.norm(scene.velocity[agent, step])), cfg)
        self.others = [i for i in range(scene.n_agents) if i != agent and scene.valid[i, step]] if cfg.collision else []
        self.hits = collisions(scene, agent, step, trajs, horizon, self.others) if cfg.collision else None
        self.base = self._apply(np.ones(self.n, dtype=bool), [(k, self.masks[k]) for k in ORDER if k in self.masks])

    def _apply(self, keep, masks):
        for name, mask in masks:
            if (keep & mask).any():
                keep = keep & mask
            elif name == "route":  # nothing left follows the route: the closest one of what is left
                closest = np.flatnonzero(keep)[int(np.argmin(self.deviation[keep]))]
                keep = np.zeros(self.n, dtype=bool)
                keep[closest] = True
        return keep

    def keep(self, b: Optional[int] = None) -> np.ndarray:
        """Indices of the trajectories kept for beta_s(a, b)."""
        keep = self.base
        if self.hits is not None and self.hits.size:
            cols = [j for j, c in enumerate(self.others) if c != b]
            keep = self._apply(keep, [("collision", ~self.hits[:, cols].any(-1))])
        return np.flatnonzero(keep)

    def stats(self, idx: np.ndarray) -> Dict[str, float]:
        """How much of the motion set was kept: count, and probability mass
        (the share of trajectories for a sampled set)."""
        mass = len(idx) / self.n if self.weights is None else float(self.weights[idx].sum() / self.weights.sum())
        return {"kept": int(len(idx)), "kept_mass": round(mass, 4)}
